import test from 'node:test';import assert from 'node:assert/strict';
import {qualifyOnce,qualifyEvidence,recoverOnce,auditValidate} from './synthetic-qualification.mjs';
const marker='VAOSQ_ABCDEF0123456789',flowId='flow_1234567890',runId='run_1234567890';
const store=()=>{const m=new Map();return {get:async k=>structuredClone(m.get(k)),put:async(k,v)=>m.set(k,structuredClone(v)),tamper:(k,v)=>m.set(k,v),raw:m};};
const wrap=o=>({content:[{type:'text',text:JSON.stringify(o)}]});
function client(opts={}){const calls=[];return {calls,tools:async()=>['ap_build_flow','ap_test_flow','ap_get_run','ap_list_runs'].filter(x=>!opts.missing?.includes(x)),call:async(method,args)=>{calls.push({method,args});if(opts.breakAt===method)throw new Error('offline secret payload');if(method==='ap_build_flow')return wrap({flowId});
if(method==='ap_test_flow')return wrap({flowRunId:runId});
if(method==='ap_get_run')return wrap({id:runId,flowId,status:'SUCCEEDED',steps:{step_1:{output:{qualMarker:opts.wrong?'BAD':marker,checksum:45,fixtureType:'VAOS_SANDBOX_V1'}}}});
if(method==='ap_list_runs')return wrap({data:[{id:runId}]});throw new Error('unknown tool');}}}
test('single test run PASS only after independent run-detail and run-list readback',async()=>{const s=store(),c=client();const v=await qualifyOnce({store:s,client:c,makeMarker:()=>marker});
 assert.equal(v.status,'PASS');assert.equal(v.audit.ok,true);assert.equal(v.checksumVerified,true);
 assert.deepEqual(c.calls.map(x=>x.method),['ap_build_flow','ap_test_flow','ap_get_run','ap_list_runs']);
 assert.equal(c.calls[0].args.steps[0].retryOnFailure,false);
 await qualifyOnce({store:s,client:c,makeMarker:()=>marker});assert.equal(c.calls.length,4);
});
test('missing mutable tools blocks before flow creation',async()=>{const s=store(),c=client({missing:['ap_test_flow']});const r=await qualifyOnce({store:s,client:c,makeMarker:()=>marker});
 assert.equal(r.status,'HOLD');assert.equal(r.reason,'AP_REQUIRED_TOOLS_DISABLED');assert.equal(c.calls.length,0);
});
test('ambiguous test submission fails closed and never resubmits on retry or recovery',async()=>{const s=store(),c=client({breakAt:'ap_test_flow'});const r=await qualifyOnce({store:s,client:c,makeMarker:()=>marker});
 assert.equal(r.phase,'TEST_SUBMITTED');assert.equal(r.status,'HOLD');await qualifyOnce({store:s,client:c,makeMarker:()=>marker});await recoverOnce({store:s,client:c});
 assert.equal(c.calls.filter(x=>x.method==='ap_test_flow').length,1);
});
test('run mismatch is HOLD and does not claim PASS',async()=>{const s=store(),c=client({wrong:true});const r=await qualifyOnce({store:s,client:c,makeMarker:()=>marker});
 assert.equal(r.status,'HOLD');assert.equal(r.phase,'READBACK_MISMATCH');
});
test('recovery queries the run only, not workflow execution',async()=>{const s=store(),c=client();
 s.raw.set('ap-qual-state',{status:'HOLD',phase:'RUN_RECORDED',flowId,runId,marker});
 const result=await recoverOnce({store:s,client:c});assert.equal(result.status,'PASS');assert.deepEqual(c.calls.map(x=>x.method),['ap_get_run']);
});
test('audit hash chain detects tampering and contains no OAuth credentials',async()=>{const s=store(),c=client();
 const r=await qualifyOnce({store:s,client:c,makeMarker:()=>marker});assert.equal(r.audit.ok,true);
 const es=s.raw.get('ap-qual-audit');assert.doesNotMatch(JSON.stringify(es),/accessToken|refreshToken|Bearer/);
 es[0].event='ALTERED';s.tamper('ap-qual-audit',es);
 assert.equal((await auditValidate(s)).ok,false);
});
