import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const web = resolve(root, "apps", "web");

const html = readFileSync(resolve(web, "index.html"), "utf8");
const login = readFileSync(resolve(web, "login.html"), "utf8");
const css = readFileSync(resolve(web, "styles.css"), "utf8");
const app = readFileSync(resolve(web, "app.mjs"), "utf8");
const workspace = readFileSync(resolve(web, "workspace.html"), "utf8");
const workspaceCss = readFileSync(resolve(web, "workspace.css"), "utf8");
const workspaceApp = readFileSync(resolve(web, "workspace.mjs"), "utf8");
const rootCommandRouter = resolve(web, "command-router.mjs");
const rlsMigration = readFileSync(resolve(root, "supabase", "migrations", "20261006223142_enable_legacy_control_plane_rls.sql"), "utf8");
const workforceMigration = readFileSync(resolve(root, "supabase", "migrations", "20261007131344_digital_workforce_v1.sql"), "utf8");
const workforceLifecycleMigration = readFileSync(resolve(root, "supabase", "migrations", "20261007133440_digital_workforce_lifecycle_v2.sql"), "utf8");
const workspaceModel = readFileSync(resolve(web, "lib", "workspace-model.mjs"), "utf8");

assert.match(html, /vayu-shastr-original\.webp/);
assert.match(html, /id="login-form"/);
assert.match(app, /\/api\/login/);
assert.match(app, /\/api\/session/);
assert.match(css, /prefers-reduced-motion/);

assert.match(workspace, /Agent Control Centre/);
assert.match(workspace, /id="domain-workspace"/);
assert.match(workspace, /id="domain-record-list"/);
assert.match(workspace, /id="domain-thread-dialog"/);
assert.match(workspace, /id="domain-thread-timeline"/);
assert.match(workspace, /data-record-tab="overview"/);
assert.match(workspace, /data-record-tab="governance"/);
assert.match(workspace, /data-record-tab="evidence"/);
assert.match(workspace, /data-record-tab="thread"/);
assert.match(workspace, /data-record-tab="raw"/);
assert.match(workspace, /id="record-overview-summary"/);
assert.match(workspace, /id="record-evidence-detail"/);
assert.match(workspace, /id="record-raw-panel"[^>]*hidden/);
assert.match(workspace, /id="domain-thread-events-raw"/);
assert.match(workspace, /id="enterprise-trace-graph"/);
assert.match(workspace, /id="trace-node-layer"/);
assert.match(workspace, /id="trace-edge-list"/);
assert.match(workspace, /id="trace-author-form"/);
assert.match(workspace, /id="trace-author-source"/);
assert.match(workspace, /id="trace-author-relation"/);
assert.match(workspace, /id="trace-author-target"/);
assert.match(workspace, /id="trace-author-reason"/);
assert.match(workspace, /id="module-approval-panel"/);
assert.match(workspace, /id="module-approval-list"/);
assert.match(workspace, /id="module-approval-count"/);
assert.match(workspace, /id="control-plane-status"/);
assert.match(workspace, /Control plane connecting/);
assert.match(workspace, /id="operational-workspace"/);
assert.match(workspace, /id="operational-summary"/);
assert.match(workspace, /id="operational-record-list"/);
assert.match(workspace, /workspace\.css/);
assert.match(workspaceApp, /\/api\/control-plane/);
assert.match(workspaceApp, /\/api\/approvals/);
assert.match(workspaceApp, /renderApprovalWorkspace/);
assert.match(workspaceApp, /renderOperationalWorkspace/);
assert.match(workspaceApp, /module-approval-list/);
assert.match(workspaceApp, /renderDomainWorkspace/);
assert.match(workspaceApp, /openDomainThread/);
assert.match(workspaceApp, /setRecordDetailTab/);
assert.match(workspaceApp, /recordEventFacts/);
assert.match(workspaceApp, /Open operational record/);
assert.match(workspaceApp, /data-domain-record-id/);
assert.match(workspaceApp, /renderEnterpriseTraceGraph/);
assert.match(workspaceApp, /submitTraceLinkProposal/);
assert.match(workspaceApp, /DIGITAL_THREAD\.CREATE_LINK/);
assert.match(workspaceApp, /\/api\/intents/);
assert.match(workspaceApp, /executeVAOSCommand/);
assert.match(workspaceApp, /resolveCommand/);
assert.match(workspaceApp, /controlPlaneStatus/);
assert.match(workspaceApp, /Control plane online/);
assert.match(workspaceApp, /Control plane unavailable/);
assert.match(workspaceApp, /from ['"]\.\/command-router\.mjs['"]/);
assert.doesNotMatch(workspaceApp, /from ['"]\.\/lib\/command-router\.mjs['"]/);
assert.equal(existsSync(rootCommandRouter), true);
const executionsApi = readFileSync(resolve(web, "api", "executions.mjs"), "utf8");
assert.match(executionsApi, /getExecutionEngine/);
assert.match(workspaceCss, /max-width: 900px/);

assert.match(workspace, /class="control-header"/);
assert.match(workspace, /class="workspace-license"/);
assert.match(workspace, /© 2026 Vāyū Shastr Pvt\. Ltd\. All Rights Reserved\./);
assert.match(workspace, /Official licensed interface of Vāyū Shastr Pvt\. Ltd\./);
assert.match(workspace, /Designed & Developed by S\. Shyam Sundhar/);
assert.match(login, /© 2026 Vāyū Shastr Pvt\. Ltd\. All Rights Reserved\./);
assert.match(css, /--vayu-gold-metallic/);
assert.match(css, /--vayu-graphite-0/);
assert.match(workspaceCss, /landscape-workspace/);
assert.match(workspaceCss, /metallic-gold-rim/);
assert.match(workspaceCss, /domain-record-table/);
assert.match(workspaceCss, /digital-thread-dialog/);
assert.match(workspaceCss, /digital-thread-timeline/);
assert.match(workspaceCss, /record-detail-tabs/);
assert.match(workspaceCss, /record-detail-panel\[hidden\]/);
assert.match(workspaceCss, /record-overview-summary/);
assert.match(workspaceCss, /workforce-contract/);
assert.match(workspaceCss, /workforce-action-dialog/);
assert.match(workspace, /id="workforce-action-dialog"/);
assert.match(workspace, /id="workforce-evidence-refs"/);
assert.match(workspaceApp, /submitWorkforceLifecycle/);
assert.match(workspaceApp, /data-workforce-action/);
assert.match(workspaceApp, /workforce-responsibilities/);
assert.match(workspaceModel, /Digital Workforce Console/);
assert.match(workspaceModel, /normalizeWorkforce/);
assert.match(workspaceCss, /enterprise-trace-canvas/);
assert.match(workspaceCss, /trace-author-panel/);
assert.match(workspaceCss, /\.control-shell\[hidden\]/);
assert.match(workspaceCss, /\.workspace-loading\[hidden\]/);

for (const table of ["server_credentials","intents","approvals","events"]) {
  assert.match(rlsMigration, new RegExp(`alter table vaos_private\\.${table} enable row level security;`, "i"));
}
assert.doesNotMatch(rlsMigration, /create\s+policy/i);
assert.match(workforceMigration, /create table if not exists vaos_private\.digital_employees/i);
assert.match(workforceMigration, /create table if not exists vaos_private\.responsibility_contracts/i);
assert.match(workforceMigration, /alter table vaos_private\.digital_employees enable row level security/i);
assert.match(workforceMigration, /revoke all on table vaos_private\.digital_employees from public, anon, authenticated, service_role/i);
assert.match(workforceMigration, /alter function public\.vaos_control_snapshot\(text\) rename to vaos_control_snapshot_core/i);
assert.match(workforceMigration, /'workforce'/i);
assert.match(workforceLifecycleMigration, /digital_employee_lifecycle_events/i);
assert.match(workforceLifecycleMigration, /WORKFORCE\.QUALIFY/i);
assert.match(workforceLifecycleMigration, /QUALIFICATION_EVIDENCE_REQUIRED/i);
assert.match(workforceLifecycleMigration, /vaos_transition_digital_employee/i);
assert.match(workforceLifecycleMigration, /revoke all on table vaos_private\.digital_employee_lifecycle_events from public, anon, authenticated, service_role/i);

assert.equal(existsSync(resolve(web, "house")), false);
assert.equal(existsSync(resolve(web, "range")), false);

console.log("VAOS web verification passed.");
