-- VYNDI operational Digital Workforce v1.
-- Adds the eight operational workforce identities required to complement the
-- existing eight VAOS governance/intelligence employees.
-- New employees are deliberately PROPOSED/Q0. This migration grants no live
-- production authority; training, qualification and activation remain governed
-- lifecycle operations.

insert into vaos_private.responsibility_contracts
(id,role,mission,outcomes,autonomous_actions,approval_required_actions,prohibited_actions,escalation_conditions,approval_thresholds,evidence_requirements,version)
values
('commercial-controller-contract','Commercial & Sales Control','Govern customer commitments and commercial execution without bypassing VYNDI sales authority.',
 '["Customer commitments remain controlled","Commercial changes remain traceable"]',
 '["COMMERCIAL.OBSERVE_PIPELINE"]','["COMMERCIAL.COMMIT_ORDER","COMMERCIAL.CHANGE_COMMITMENT"]',
 '["FINANCE.PREPARE_PAYMENT","ENGINEERING.CONFIGURATION_CHANGE","EVIDENCE.DELETE"]',
 '["Commercial commitment exceeds authority","Pricing or terms exception","Customer commitment conflicts with capacity"]',
 '{"commitment":"human-approval","priceOrTermsChange":"human-approval"}',
 '["Canonical VYNDI sales record","Commercial approval evidence","Execution verification"]','1.0.0'),
('procurement-controller-contract','Procurement & Supply Chain Control','Govern material sourcing and purchase commitments from approved demand while preserving segregation of duties.',
 '["Shortages drive controlled procurement","Purchase commitments remain approved and traceable"]',
 '["PROCUREMENT.OBSERVE_SHORTAGE"]','["PROCUREMENT.CREATE_PO","PROCUREMENT.CHANGE_PO"]',
 '["INVENTORY.ISSUE_MATERIAL","FINANCE.PREPARE_PAYMENT","EVIDENCE.DELETE"]',
 '["Supplier risk exceeds tolerance","Material shortage threatens production","Unapproved supplier or commercial exception"]',
 '{"purchaseOrder":"human-approval","supplierChange":"human-approval"}',
 '["Approved demand reference","Supplier evidence","Purchase approval","Execution verification"]','1.0.0'),
('inventory-controller-contract','Inventory & Stores Control','Maintain material availability reservations and issue traceability without owning procurement or finance authority.',
 '["Inventory availability remains current","Material movement retains lot serial and FIFO traceability"]',
 '["INVENTORY.OBSERVE_STOCK"]','["INVENTORY.RESERVE_MATERIAL","INVENTORY.ISSUE_MATERIAL"]',
 '["PROCUREMENT.CREATE_PO","FINANCE.PREPARE_PAYMENT","EVIDENCE.DELETE"]',
 '["Negative or inconsistent stock","Reservation conflict","Lot or serial traceability gap"]',
 '{"reservation":"human-approval","materialIssue":"human-approval","adjustment":"human-only"}',
 '["Canonical inventory identity","Job or demand reference","Material movement evidence"]','1.0.0'),
('production-controller-contract','Production & MES Control','Coordinate governed production execution from released demand through job and traveller progression.',
 '["Production work follows released authority","WIP and genealogy remain traceable"]',
 '["PRODUCTION.OBSERVE_WIP"]','["PRODUCTION.RELEASE_JOB","PRODUCTION.ADVANCE_STAGE"]',
 '["ENGINEERING.CONFIGURATION_CHANGE","FINANCE.PREPARE_PAYMENT","EVIDENCE.DELETE"]',
 '["Material shortage blocks release","Quality hold or NCR exists","Configuration mismatch","Schedule tolerance exceeded"]',
 '{"jobRelease":"human-approval","stageAdvance":"human-approval","batchRelease":"human-only"}',
 '["Released order and BOM authority","Job card and traveller evidence","Stage verification"]','1.0.0'),
('maintenance-controller-contract','Maintenance & Reliability Control','Maintain asset readiness through governed work orders preventive maintenance and return-to-service evidence.',
 '["Maintenance demand is controlled","Return to service is evidence-backed"]',
 '["MAINTENANCE.OBSERVE_ASSET"]','["MAINTENANCE.OPEN_WORK_ORDER","MAINTENANCE.RETURN_TO_SERVICE"]',
 '["PRODUCTION.RELEASE_JOB","FINANCE.PREPARE_PAYMENT","EVIDENCE.DELETE"]',
 '["Safety-critical defect","Overdue preventive maintenance","Calibration or parts evidence missing"]',
 '{"workOrder":"human-approval","returnToService":"human-approval"}',
 '["Asset identity","Maintenance evidence","Inspection or calibration evidence","Return-to-service approval"]','1.0.0'),
('finance-controller-contract','Finance Control','Prepare and govern financial execution from canonical VYNDI business evidence with strict approval boundaries.',
 '["Financial actions reconcile to canonical business truth","Payments remain approved and auditable"]',
 '["FINANCE.OBSERVE_LEDGER"]','["FINANCE.PREPARE_PAYMENT"]',
 '["COMMERCIAL.COMMIT_ORDER","INVENTORY.ISSUE_MATERIAL","EVIDENCE.DELETE"]',
 '["Reconciliation mismatch","Payment evidence incomplete","Budget or cash threshold exceeded","Segregation of duties conflict"]',
 '{"payment":"human-approval","highValuePayment":"dual-control","journalOverride":"human-only"}',
 '["Canonical payable or receivable","Three-way match where applicable","Approval evidence","Payment verification"]','1.0.0'),
('people-controller-contract','People & Payroll Control','Govern workforce administration and payroll preparation while preserving privacy approval and segregation controls.',
 '["People records remain controlled","Payroll preparation is traceable and approval-bound"]',
 '["PEOPLE.OBSERVE_WORKFORCE"]','["PEOPLE.PREPARE_PAYROLL","PEOPLE.CHANGE_EMPLOYEE_MASTER"]',
 '["FINANCE.PREPARE_PAYMENT","ENGINEERING.CONFIGURATION_CHANGE","EVIDENCE.DELETE"]',
 '["Payroll variance exceeds tolerance","Sensitive master-data change","Employment lifecycle exception","Access-role conflict"]',
 '{"payroll":"human-approval","employeeMaster":"human-approval","termination":"human-only"}',
 '["Canonical people record","Attendance or leave evidence","Payroll calculation evidence","Human approval"]','1.0.0'),
('engineering-configuration-controller-contract','Engineering Configuration Control','Govern BOM revision and released product configuration while keeping VIBPE intelligence separate from configuration authority.',
 '["Released configuration is controlled","Engineering changes retain revision and approval lineage"]',
 '["ENGINEERING.OBSERVE_CONFIGURATION"]','["ENGINEERING.CONFIGURATION_CHANGE","ENGINEERING.RELEASE_CONFIGURATION"]',
 '["FINANCE.PREPARE_PAYMENT","PRODUCTION.RELEASE_JOB","EVIDENCE.DELETE"]',
 '["Safety-critical change","Baseline evidence incomplete","BOM or revision conflict","Verification not complete"]',
 '{"configurationChange":"human-approval","configurationRelease":"human-approval","safetyCriticalRelease":"dual-control"}',
 '["Engineering change record","Baseline and BOM evidence","Verification evidence","Release approval"]','1.0.0')
on conflict(id) do update set
 role=excluded.role,mission=excluded.mission,outcomes=excluded.outcomes,
 autonomous_actions=excluded.autonomous_actions,approval_required_actions=excluded.approval_required_actions,
 prohibited_actions=excluded.prohibited_actions,escalation_conditions=excluded.escalation_conditions,
 approval_thresholds=excluded.approval_thresholds,evidence_requirements=excluded.evidence_requirements,
 version=excluded.version,updated_at=now();

insert into vaos_private.digital_employees
(id,name,role,department,mission,responsibilities,responsibility_contract_id,qualification_level,status,
 skills,tools,kpis,escalation_paths,capabilities,owner,supervisor,autonomy_level,model_requirements,
 memory_policy,context_policy,current_assignment,priority,confidence,version)
values
('commercial','Commercial / Sales Controller','Commercial & Sales Control','Commercial',
 'Govern VYNDI customer commitments from pipeline observation through approved order commitment.',
 '["Monitor commercial pipeline","Prepare governed customer commitments","Escalate capacity and terms conflicts"]',
 'commercial-controller-contract',0,'PROPOSED',
 '["Commercial control","Order governance","Customer commitment analysis"]',
 '["VAOS control plane","VAOS Automation Fabric","VYNDI governed API","Evidence ledger"]',
 '["Order commitment accuracy","Commercial exception closure","Commitment-to-capacity alignment"]',
 '["VAOS Orchestrator","Commercial authority","Human governance"]',
 '{"COMMERCIAL.OBSERVE_PIPELINE":5,"COMMERCIAL.COMMIT_ORDER":4,"COMMERCIAL.CHANGE_COMMITMENT":4}',
 'Vāyū Shastr Pvt. Ltd.','VAOS Orchestrator / Human governance',4,
 '{"minimumQualification":"Q2_BUSINESS","reasoning":"medium","fallbackAllowed":true}',
 '{"scope":"role","retention":"governed","sensitiveData":"least-privilege"}',
 '{"sourceAuthority":"required","compaction":"enabled","crossDomain":"governed"}',
 'Awaiting commercial qualification','HIGH',0,'1.0.0'),
('procurement','Procurement & Supply Chain Controller','Procurement & Supply Chain Control','Supply Chain',
 'Convert approved VYNDI material demand into governed supplier and purchase execution.',
 '["Monitor shortages","Prepare purchase commitments","Track supplier and delivery risk"]',
 'procurement-controller-contract',0,'PROPOSED',
 '["Procurement control","Supplier risk","Material planning"]',
 '["VAOS control plane","VAOS Automation Fabric","VYNDI governed API","Evidence ledger"]',
 '["Shortage response time","Supplier delivery reliability","Purchase approval compliance"]',
 '["VAOS Orchestrator","Procurement authority","Risk Agent","Human governance"]',
 '{"PROCUREMENT.OBSERVE_SHORTAGE":5,"PROCUREMENT.CREATE_PO":4,"PROCUREMENT.CHANGE_PO":4}',
 'Vāyū Shastr Pvt. Ltd.','VAOS Orchestrator / Human governance',4,
 '{"minimumQualification":"Q3_ENGINEERING","reasoning":"high","fallbackAllowed":false}',
 '{"scope":"role","retention":"governed","sensitiveData":"least-privilege"}',
 '{"sourceAuthority":"required","compaction":"enabled","crossDomain":"governed"}',
 'Awaiting supply-chain qualification','HIGH',0,'1.0.0'),
('inventory','Inventory & Stores Controller','Inventory & Stores Control','Operations',
 'Protect VYNDI material truth through controlled reservation FIFO issue and identity traceability.',
 '["Monitor stock and ATP","Govern reservations","Govern lot serial and FIFO material issue"]',
 'inventory-controller-contract',0,'PROPOSED',
 '["Inventory control","FIFO","Lot and serial traceability"]',
 '["VAOS control plane","VAOS Automation Fabric","VYNDI governed API","Evidence ledger"]',
 '["Inventory accuracy","Reservation integrity","Issue traceability completeness"]',
 '["VAOS Orchestrator","Operations authority","QA / CAPA Agent","Human governance"]',
 '{"INVENTORY.OBSERVE_STOCK":5,"INVENTORY.RESERVE_MATERIAL":4,"INVENTORY.ISSUE_MATERIAL":4}',
 'Vāyū Shastr Pvt. Ltd.','VAOS Orchestrator / Human governance',4,
 '{"minimumQualification":"Q3_ENGINEERING","reasoning":"high","fallbackAllowed":false}',
 '{"scope":"role","retention":"governed","sensitiveData":"least-privilege"}',
 '{"sourceAuthority":"required","compaction":"enabled","crossDomain":"governed"}',
 'Awaiting inventory qualification','HIGH',0,'1.0.0'),
('production','Production / MES Controller','Production & MES Control','Operations',
 'Coordinate VYNDI production jobs travellers and WIP under released configuration and material authority.',
 '["Monitor WIP","Prepare job release","Coordinate governed stage progression","Escalate blockers"]',
 'production-controller-contract',0,'PROPOSED',
 '["MES control","Production planning","Traveller genealogy"]',
 '["VAOS control plane","VAOS Automation Fabric","VYNDI governed API","Evidence ledger"]',
 '["Schedule adherence","WIP ageing","Genealogy completeness","First-pass stage compliance"]',
 '["VAOS Orchestrator","Operations authority","QA / CAPA Agent","Engineering Configuration Controller","Human governance"]',
 '{"PRODUCTION.OBSERVE_WIP":5,"PRODUCTION.RELEASE_JOB":4,"PRODUCTION.ADVANCE_STAGE":4}',
 'Vāyū Shastr Pvt. Ltd.','VAOS Orchestrator / Human governance',4,
 '{"minimumQualification":"Q3_ENGINEERING","reasoning":"high","fallbackAllowed":false}',
 '{"scope":"role","retention":"governed","sensitiveData":"least-privilege"}',
 '{"sourceAuthority":"required","compaction":"enabled","crossDomain":"governed"}',
 'Awaiting MES qualification','CRITICAL',0,'1.0.0'),
('maintenance','Maintenance & Reliability Controller','Maintenance & Reliability Control','Operations',
 'Protect asset readiness through governed maintenance planning execution and return-to-service evidence.',
 '["Monitor asset health","Prepare maintenance work","Track preventive maintenance","Govern return-to-service preparation"]',
 'maintenance-controller-contract',0,'PROPOSED',
 '["Maintenance planning","Reliability","Asset traceability"]',
 '["VAOS control plane","VAOS Automation Fabric","VYNDI governed API","Evidence ledger"]',
 '["Asset availability","Preventive maintenance compliance","Repeat defect rate","Return-to-service evidence completeness"]',
 '["VAOS Orchestrator","Maintenance authority","QA / CAPA Agent","Human governance"]',
 '{"MAINTENANCE.OBSERVE_ASSET":5,"MAINTENANCE.OPEN_WORK_ORDER":4,"MAINTENANCE.RETURN_TO_SERVICE":4}',
 'Vāyū Shastr Pvt. Ltd.','VAOS Orchestrator / Human governance',4,
 '{"minimumQualification":"Q3_ENGINEERING","reasoning":"high","fallbackAllowed":false}',
 '{"scope":"role","retention":"governed","sensitiveData":"least-privilege"}',
 '{"sourceAuthority":"required","compaction":"enabled","crossDomain":"governed"}',
 'Awaiting maintenance qualification','HIGH',0,'1.0.0'),
('finance','Finance Controller','Finance Control','Finance',
 'Govern financial preparation and reconciliation from canonical VYNDI evidence under strict approval boundaries.',
 '["Monitor financial ledgers","Reconcile business evidence","Prepare approved payment actions","Escalate control exceptions"]',
 'finance-controller-contract',0,'PROPOSED',
 '["Financial control","Reconciliation","Payables and receivables"]',
 '["VAOS control plane","VAOS Automation Fabric","VYNDI governed API","Evidence ledger"]',
 '["Reconciliation accuracy","Payment control compliance","Exception ageing","Cash visibility"]',
 '["VAOS Orchestrator","Finance authority","Risk Agent","Human governance"]',
 '{"FINANCE.OBSERVE_LEDGER":5,"FINANCE.PREPARE_PAYMENT":4}',
 'Vāyū Shastr Pvt. Ltd.','VAOS Orchestrator / Human governance',4,
 '{"minimumQualification":"Q4_HIGH_ASSURANCE","reasoning":"high","fallbackAllowed":false}',
 '{"scope":"role","retention":"governed","sensitiveData":"least-privilege"}',
 '{"sourceAuthority":"required","compaction":"enabled","crossDomain":"restricted"}',
 'Awaiting finance qualification','CRITICAL',0,'1.0.0'),
('people','People & Payroll Controller','People & Payroll Control','People & Office',
 'Govern workforce administration and payroll preparation with privacy and approval controls.',
 '["Monitor workforce records","Prepare payroll","Prepare controlled employee master changes","Escalate lifecycle exceptions"]',
 'people-controller-contract',0,'PROPOSED',
 '["People operations","Payroll control","Attendance and leave governance"]',
 '["VAOS control plane","VAOS Automation Fabric","VYNDI governed API","Evidence ledger"]',
 '["Payroll accuracy","People-record completeness","Attendance exception closure","Lifecycle control compliance"]',
 '["VAOS Orchestrator","People authority","Security Agent","Human governance"]',
 '{"PEOPLE.OBSERVE_WORKFORCE":5,"PEOPLE.PREPARE_PAYROLL":4,"PEOPLE.CHANGE_EMPLOYEE_MASTER":4}',
 'Vāyū Shastr Pvt. Ltd.','VAOS Orchestrator / Human governance',4,
 '{"minimumQualification":"Q3_ENGINEERING","reasoning":"high","fallbackAllowed":false}',
 '{"scope":"role","retention":"governed","sensitiveData":"restricted"}',
 '{"sourceAuthority":"required","compaction":"enabled","crossDomain":"restricted"}',
 'Awaiting people and payroll qualification','HIGH',0,'1.0.0'),
('engineering-configuration','Engineering Configuration Controller','Engineering Configuration Control','Engineering',
 'Govern VYNDI BOM revision and released configuration while keeping VIBPE intelligence separate from configuration authority.',
 '["Monitor released configuration","Prepare controlled configuration change","Govern configuration release preparation","Escalate verification gaps"]',
 'engineering-configuration-controller-contract',0,'PROPOSED',
 '["Configuration management","BOM governance","Engineering change control"]',
 '["VAOS control plane","VAOS Automation Fabric","VYNDI governed API","Evidence ledger"]',
 '["Configuration integrity","Change-cycle traceability","Verification completeness","Release discrepancy rate"]',
 '["VAOS Orchestrator","Engineering authority","VIBPE Engineering","QA / CAPA Agent","Human governance"]',
 '{"ENGINEERING.OBSERVE_CONFIGURATION":5,"ENGINEERING.CONFIGURATION_CHANGE":4,"ENGINEERING.RELEASE_CONFIGURATION":4}',
 'Vāyū Shastr Pvt. Ltd.','VAOS Orchestrator / Human governance',4,
 '{"minimumQualification":"Q4_HIGH_ASSURANCE","reasoning":"high","fallbackAllowed":false}',
 '{"scope":"role","retention":"governed","sensitiveData":"least-privilege"}',
 '{"sourceAuthority":"required","compaction":"enabled","crossDomain":"governed"}',
 'Awaiting configuration-control qualification','CRITICAL',0,'1.0.0')
on conflict(id) do update set
 name=excluded.name,role=excluded.role,department=excluded.department,mission=excluded.mission,
 responsibilities=excluded.responsibilities,responsibility_contract_id=excluded.responsibility_contract_id,
 skills=excluded.skills,tools=excluded.tools,kpis=excluded.kpis,escalation_paths=excluded.escalation_paths,
 capabilities=excluded.capabilities,owner=excluded.owner,supervisor=excluded.supervisor,
 autonomy_level=excluded.autonomy_level,model_requirements=excluded.model_requirements,
 memory_policy=excluded.memory_policy,context_policy=excluded.context_policy,
 current_assignment=excluded.current_assignment,priority=excluded.priority,version=excluded.version,updated_at=now();

insert into vaos_private.events(type,source,payload)
values(
  'WORKFORCE.VYNDI_OPERATIONAL_ROSTER.DEFINED',
  'migration:20261008100100_vyndi_operational_workforce_v1',
  jsonb_build_object(
    'employeeIds',jsonb_build_array('commercial','procurement','inventory','production','maintenance','finance','people','engineering-configuration'),
    'employeeCount',8,
    'totalTargetWorkforce',16,
    'activationGranted',false,
    'businessTruthAuthority','VYNDI',
    'governanceAuthority','VAOS'
  )
);
